### ISSUE TITLE
please update to swift2.0 for Xcode 7.0

### ISSUE THREAD

**Issue by wongben** [indragiek/DominantColor#27]
please update to swift2.0 for Xcode 7.0,thanks

**Comment by FBente** [comment]
In this context there are two more warnings appearing during the build process. Please update the code to avoid these and be future save.

/DominantColor/ColorDifference.swift:27:33: Curried function declaration syntax will be removed in a future version of Swift; use a single parameter list

/DominantColor/ColorDifference.swift:52:35: Curried function declaration syntax will be removed in a future version of Swift; use a single parameter list

**Comment by metasmile** [comment]
Fixed in #29
