### ISSUE TITLE
Compiles fine in Simulator but doesn't compile on iPhone 7 Plus device?

### ISSUE THREAD

**Issue by seenoevo** [indragiek/DominantColor#35]
I'm using your code in my Swift 3 app and it works fine in the simulator but when I try to run it on my 7 Plus device, it doesn't compile, complaining that `value of UIImage has no member dominantColors`.

The weird thing is running your project as a stand-alone works fine on my device.

Xcode does see the DominantColor framework when I try to import it using `import DominantColor`, so I'm really at a lost.

Any clues?

**Comment by indragiek** [comment]
This issue is likely no longer relevant, please try on the latest release (v0.2.1) and reopen the issue if it persists. Thanks!
