### ISSUE TITLE
Does CIE2000 have high cost?

### ISSUE THREAD

**Issue by jeong-tae** [indragiek/DominantColor#37]
I have own implementation for CIE76 and CIE2000.

For 5,000 samples, it take 10times than CIE76 in my computer.

Does CIE2000 is expensive calculation? I am not sure that i make correctly or not.
Plz someone comment this issue!

**Comment by indragiek** [comment]
Yes, CIE2000 is expected to perform worse but it's hard to say how much worse, since it depends on a lot of different variables. Please post benchmark results and we can take a closer look if needed. Closing this issue for now.
